# Identificadors del projecte (extrets del teu log)
sonar.projectKey=pes2526q2-12-gei-upc-a_agendat-flutter-frontend
sonar.organization=pes2526q2-12-gei-upc-a

# On està el codi i on estan els tests
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=**/*_test.dart

# Cobertura de codi (CRÍTIC per a Flutter)
# Aquesta línia permet que SonarCloud llegeixi els resultats de 'flutter test --coverage'
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Exclusions de fitxers generats i carpetes de plataforma
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,**/build/**,**/android/**,**/ios/**,**/web/**,**/linux/**,**/macos/**,**/windows/**

# Codificació
sonar.sourceEncoding=UTF-8