sonar.projectKey=pes2526q2-12-gei-upc-a_agendat-flutter-frontend
sonar.organization=pes2526q2-12-gei-upc-a

# Source code directory
sonar.sources=lib

# Exclude build outputs, generated files, and platform-specific code
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,**/build/**,**/android/**,**/ios/**,**/web/**,**/linux/**,**/macos/**,**/windows/**

# Test directory
sonar.tests=test
sonar.test.inclusions=**/*_test.dart

# Dart/Flutter specific settings
sonar.sourceEncoding=UTF-8
